server:
  port: 8080
  address: 0.0.0.0
  session:

    persistent: true
  contextPath: /api/

  tomcat:
    accessLogEnabled: true
    protocolHeader: x-forwarded-proto
    remoteIpHeader: x-forwarded-for
    basedir:
    backgroundProcessorDelay: 30


spring: 
  application:
    name: "GoMovie"

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/GoMovie?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    validationQuery: SELECT 1
    test-while-idle: true
    test-on-borrow: true
    
  jpa:
    hibernate:
      ddl-auto: "create"
    show-sql: true
  cache:
    type: redis
    
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
    timeout: 0


security: 
  basic:
    enabled: true

endpoints: 
  sensitive: false

management:
  security:
    role: "admin"
    enabled: true
  context-path: "/manage"
  
